/*
 *
 * Émile ROYER
 * TP 3, v1.4
 *
 */
package superpuissance4;

import java.util.Random;

/**
 * Crée l'interface graphique
 *
 * @author Émile ROYER
 */
public class fenetreJeu extends javax.swing.JFrame {

	// attributs rajoutés depuis la classe partie
	Joueur[] ListeJoueur = new Joueur[2];
	Grille grilleJeu = new Grille();
	Joueur joueurCourant;

	/**
	 * Creates new form fenetreJeu
	 */
	public fenetreJeu() {
		initComponents();
		// on cache les deux panneaux suivant ( en créant deux boolean initailisé à  faux)
		panneau_info_joueurs.setVisible(false); // ce panneau est maintenant caché
		panneau_info_partie.setVisible(false); // on fait de même pour le panneau information partie
		// on rendra ces panneaux visibles seuleument lorsqu'on aura cliqué sur le bouton "Démarrer la partie"

		for (int i = 0; i < grilleJeu.nb_lignes; i++) {
			for (int j = 0; j < grilleJeu.nb_colonnes; j++) {
				CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.Cellules[i][j]); // création d'une nouvelle cellule graphique appelé cellGraph
				panneau_grille.add(cellGraph); // on ajoute les éléments cellGraph à notre panneau de jeu
			}
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur1 = new javax.swing.JTextField();
        nom_joueur2 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        panneau_info_joueurs = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_j1_nom = new javax.swing.JLabel();
        lbl_j1_couleur = new javax.swing.JLabel();
        lbl_j1_desint = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_j2_nom = new javax.swing.JLabel();
        lbl_j2_couleur = new javax.swing.JLabel();
        lbl_j2_desint = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panneau_info_partie = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        message = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_col_0 = new javax.swing.JButton();
        btn_col_1 = new javax.swing.JButton();
        btn_col_2 = new javax.swing.JButton();
        btn_col_3 = new javax.swing.JButton();
        btn_col_4 = new javax.swing.JButton();
        btn_col_5 = new javax.swing.JButton();
        btn_col_6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(254, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 672, 576));

        panneau_creation_partie.setBackground(new java.awt.Color(99, 224, 99));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom du joueur 1 :");
        panneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jLabel2.setText("Nom du joueur 2 :");
        panneau_creation_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        panneau_creation_partie.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, -1));
        panneau_creation_partie.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, -1));

        btn_start.setText("Démarrer la partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        getContentPane().add(panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 290, 170));

        panneau_info_joueurs.setBackground(new java.awt.Color(99, 224, 99));
        panneau_info_joueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Désintégrateurs :");
        panneau_info_joueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setText("Joueur 1 :");
        panneau_info_joueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel6.setText("Couleur :");
        panneau_info_joueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbl_j1_nom.setText("nomJoueur1");
        panneau_info_joueurs.add(lbl_j1_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        lbl_j1_couleur.setText("couleurJoueur1");
        panneau_info_joueurs.add(lbl_j1_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        lbl_j1_desint.setText("nbdesintJoueur1");
        panneau_info_joueurs.add(lbl_j1_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        panneau_info_joueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, 10));

        jLabel7.setText("Désintégrateurs :");
        panneau_info_joueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel8.setText("Joueur 2 :");
        panneau_info_joueurs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel9.setText("Couleur :");
        panneau_info_joueurs.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lbl_j2_nom.setText("nomJoueur2");
        panneau_info_joueurs.add(lbl_j2_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        lbl_j2_couleur.setText("couleurJoueur2");
        panneau_info_joueurs.add(lbl_j2_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        lbl_j2_desint.setText("nbdesintJoueur2");
        panneau_info_joueurs.add(lbl_j2_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel10.setText("Informations joueurs :");
        panneau_info_joueurs.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(panneau_info_joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 290, 250));

        panneau_info_partie.setBackground(new java.awt.Color(99, 224, 99));
        panneau_info_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel3.setText("Informations jeu : ");
        panneau_info_partie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel11.setText("Joueur courant :");
        panneau_info_partie.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbl_jcourant.setText("nomJoueur");
        panneau_info_partie.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        message.setViewportView(jTextArea1);

        panneau_info_partie.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, 130));

        getContentPane().add(panneau_info_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 290, 260));

        btn_col_0.setText("1");
        btn_col_0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_col_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btn_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 50, -1, -1));

        btn_col_1.setText("2");
        btn_col_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_col_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btn_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 50, -1, -1));

        btn_col_2.setText("3");
        btn_col_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_col_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btn_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 50, -1, -1));

        btn_col_3.setText("4");
        btn_col_3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_col_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btn_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 50, -1, -1));

        btn_col_4.setText("5");
        btn_col_4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_col_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btn_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 50, -1, -1));

        btn_col_5.setText("6");
        btn_col_5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_col_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btn_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 50, -1, -1));

        btn_col_6.setText("7");
        btn_col_6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_col_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btn_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 50, -1, -1));

        setBounds(0, 0, 1210, 830);
    }// </editor-fold>//GEN-END:initComponents

	// code qui permet de faire une action lorsqu'on clique sur le bouton "Démarrer la partie"
    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed

		panneau_info_joueurs.setVisible(true); // on rend visible le panneau d'informations des joueurs en modifant sont boolean à vrai
		panneau_info_partie.setVisible(true); // on fait de même pour le panneau d'informations de la partie
		initialiserPartie();
		panneau_grille.repaint(); // raffraichi l'affichage de la partie et le redessine complètement
		grilleJeu.afficherGrillesurConsole();
		btn_start.setEnabled(false); // on désactive le btn_start pour pas que les utilisateurs s'amusent à rafraichir la partie et avoir une nouvelle grille
    }//GEN-LAST:event_btn_startActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(fenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(fenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(fenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(fenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new fenetreJeu().setVisible(true);
			}
		});
	}

	public void initialiserPartie() {
		Random rnd = new Random();

		attribuerCouleursAuxJoueurs();

		lbl_j1_nom.setText(ListeJoueur[0].Nom);
		lbl_j1_couleur.setText(ListeJoueur[0].Couleur);
		lbl_j1_desint.setText(ListeJoueur[0].nombreDesintegrateurs + "");

		lbl_j2_nom.setText(ListeJoueur[1].Nom);
		lbl_j2_couleur.setText(ListeJoueur[1].Couleur);
		lbl_j2_desint.setText(ListeJoueur[1].nombreDesintegrateurs + "");

		/* Crée la grille si elle n'existait pas, et la vide si elle existait */
		grilleJeu = new Grille();

		/* Distribution des jetons */
		for (int i = 0; i < ListeJoueur.length; i++) {
			for (int j = 0; j < ListeJoueur[i].ListeJetons.length; j++) {
				ListeJoueur[i].ListeJetons[j] = new Jeton(ListeJoueur[i].lireCouleur());
			}
			ListeJoueur[i].nombreJetonsRestants = 21;
		}

		/* Détermination du joueur courant */
		joueurCourant = ListeJoueur[rnd.nextInt(2)];

		lbl_jcourant.setText(joueurCourant.Nom);

		/*
		* Placement des trous noirs.
		* Si il y a déjà un trou noir à l'endroit où on peut en placer un, on
		* réessaye à un autre endroit.
		* On en profite pour placer les deux désintégrateurs cachés.
		 */
		for (int k = 0; k < 5; k++) {
			int i = rnd.nextInt(grilleJeu.nb_lignes);
			int j = rnd.nextInt(grilleJeu.nb_colonnes);
			if (grilleJeu.Cellules[i][j].presenceTrouNoir()) {
				k--;
			} else {
				grilleJeu.placerTrouNoir(i, j);
				if (k < 2) {
					grilleJeu.placerDesintegrateur(i, j);
				}
			}
		}

		/* Placement des 3 désintégrateurs restants */
		for (int k = 0; k < 3; k++) {
			int i = rnd.nextInt(grilleJeu.nb_lignes);
			int j = rnd.nextInt(grilleJeu.nb_colonnes);

			/*
			* Il ne faut pas qu'il y ait un désintégrateur sur la case, ni un
			* trou noir (seulement deux désintégrateurs sur des cases de trou noir).
			 */
			if (grilleJeu.Cellules[i][j].presenceDesintegrateur() || grilleJeu.Cellules[i][j].presenceTrouNoir()) {
				k--;
			} else {
				grilleJeu.placerDesintegrateur(i, j);
			}
		}
	}

	public void attribuerCouleursAuxJoueurs() {
		Random rnd = new Random();
		int index;

		String nomJoueur1 = nom_joueur1.getText(); // le nom joueur est issu de ce qui à été tapé dans la cellule
		ListeJoueur[0] = new Joueur(nomJoueur1);

		String nomJoueur2 = nom_joueur2.getText(); // on fait la même chose que pour le joueur 1
		ListeJoueur[1] = new Joueur(nomJoueur2);

		index = rnd.nextInt(2);

		/* On colore le nom des couleurs pour plus de lisibilité */
		ListeJoueur[index].affecterCouleur("rouge");
		ListeJoueur[1 - index].affecterCouleur("jaune");

		System.out.println(ListeJoueur[0].Nom + " prend la couleur "
				+ ListeJoueur[0].lireCouleur() + ", tandis que " + ListeJoueur[1].Nom
				+ " prend la couleur " + ListeJoueur[1].lireCouleur() + ".");

//		/*
//		* On colore le nom des joueurs avec leur couleur pour plus de lisibilité
//		*/
//		ListeJoueur[index].Nom = "\033[91m" + ListeJoueur[index].Nom + "\033[0m";
//		ListeJoueur[1-index].Nom = "\033[93m" + ListeJoueur[1-index].Nom + "\033[0m";
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_col_0;
    private javax.swing.JButton btn_col_1;
    private javax.swing.JButton btn_col_2;
    private javax.swing.JButton btn_col_3;
    private javax.swing.JButton btn_col_4;
    private javax.swing.JButton btn_col_5;
    private javax.swing.JButton btn_col_6;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_j1_couleur;
    private javax.swing.JLabel lbl_j1_desint;
    private javax.swing.JLabel lbl_j1_nom;
    private javax.swing.JLabel lbl_j2_couleur;
    private javax.swing.JLabel lbl_j2_desint;
    private javax.swing.JLabel lbl_j2_nom;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JScrollPane message;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_info_joueurs;
    private javax.swing.JPanel panneau_info_partie;
    // End of variables declaration//GEN-END:variables
}
